# Generated by Django 3.2.18 on 2023-03-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_academy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='coach',
            name='picture',
            field=models.ImageField(default='static/images/coaches/avatar.png', upload_to='static/images/coaches/'),
        ),
    ]
