# Generated by Django 4.1.7 on 2023-03-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='position',
            field=models.CharField(max_length=67, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='team',
            field=models.ManyToManyField(related_name='coaches', to='sport_academy.team'),
        ),
    ]
