# Generated by Django 4.1.7 on 2023-03-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_academy', '0002_coach_position_alter_coach_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='coaches', to='sport_academy.team'),
        ),
    ]
