# Generated by Django 3.2.18 on 2023-03-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_academy', '0002_auto_20230329_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='picture',
            field=models.ImageField(default='/coaches/avatar.png', upload_to='coaches/'),
        ),
    ]
