# Generated by Django 4.1.7 on 2023-03-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_academy', '0003_alter_coach_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
