# Generated by Django 4.1.7 on 2023-03-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_academy', '0004_player_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='picture_url',
            field=models.CharField(default='/images/players/pyatov.png', max_length=255),
            preserve_default=False,
        ),
    ]
