# Generated by Django 3.2.18 on 2023-03-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_academy', '0004_alter_coach_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='player',
            name='picture',
            field=models.ImageField(default='players/avatar.png', upload_to='players/'),
        ),
    ]
