# Generated by Django 3.2.18 on 2023-03-31 18:06

from django.db import migrations
from django.db.migrations import RunPython


def func(apps, schema_editor):
    from django.core.management import call_command
    call_command('loaddata', 'fixture_out.json')


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sport_academy', '0005_auto_20230329_2327'),
    ]

    operations = [
        RunPython(func, reverse_func),
    ]
